version: '3.9'

services:
  frontend:
    build: ./recipe-app
    ports: 
      - "3000:3000"
    container_name: cmpt372-frontend
  server:
    build: ./backend
    ports: 
      - "4000:4000"
    container_name: cmpt372-server
  db:
    image: 'postgres'
    ports:
      - '4444:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'

      