# docker/frontend.Dockerfile
FROM node:18.13 as builder

WORKDIR /recipe-app

# Install the Angular CLI globally
RUN npm install -g @angular/cli

COPY ../recipe-app/package*.json ./
RUN npm install

COPY ../recipe-app .

RUN npm run build

EXPOSE 4200

CMD ["npm", "start"]